/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDKG__factory } from "./IDKG__factory";
export { IDKGRequest__factory } from "./IDKGRequest__factory";
export { IVerifier__factory } from "./IVerifier__factory";
