/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as libs from "./libs";
export { DKG__factory } from "./DKG__factory";
