/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface IDKGInterface extends utils.Interface {
  functions: {
    "generateDistributedKey()": FunctionFragment;
    "startTally()": FunctionFragment;
    "submitRound1Contribution()": FunctionFragment;
    "submitRound2Contribution()": FunctionFragment;
    "submitTallyContribution()": FunctionFragment;
    "submitTallyResult()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "generateDistributedKey"
      | "startTally"
      | "submitRound1Contribution"
      | "submitRound2Contribution"
      | "submitTallyContribution"
      | "submitTallyResult"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "generateDistributedKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startTally",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitRound1Contribution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitRound2Contribution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitTallyContribution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitTallyResult",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "generateDistributedKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTally", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitRound1Contribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRound2Contribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTallyContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTallyResult",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IDKG extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDKGInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    generateDistributedKey(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startTally(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitRound1Contribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitRound2Contribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitTallyContribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitTallyResult(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  generateDistributedKey(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startTally(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitRound1Contribution(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitRound2Contribution(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitTallyContribution(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitTallyResult(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    generateDistributedKey(overrides?: CallOverrides): Promise<void>;

    startTally(overrides?: CallOverrides): Promise<void>;

    submitRound1Contribution(overrides?: CallOverrides): Promise<void>;

    submitRound2Contribution(overrides?: CallOverrides): Promise<void>;

    submitTallyContribution(overrides?: CallOverrides): Promise<void>;

    submitTallyResult(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    generateDistributedKey(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startTally(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitRound1Contribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitRound2Contribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitTallyContribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitTallyResult(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    generateDistributedKey(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startTally(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitRound1Contribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitRound2Contribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitTallyContribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitTallyResult(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
