/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDKG } from "./IDKG";
export type { IDKGRequest } from "./IDKGRequest";
export type { IVerifier } from "./IVerifier";
export * as factories from "./factories";
export { IDKG__factory } from "./factories/IDKG__factory";
export { IDKGRequest__factory } from "./factories/IDKGRequest__factory";
export { IVerifier__factory } from "./factories/IVerifier__factory";
